hyper-test-4 { connection: 'upgrade',
host: 'hypertest.cloudoki.com',
'content-length': '7007',
accept: '*/*',
'user-agent': 'GitHub-Hookshot/375c44e',
'x-github-event': 'push',
'x-github-delivery': '77edf080-299f-11e6-80a6-9dfbc40db237',
'content-type': 'application/json' }


{
repository:
 { id: 60270865,
   name: 'cn-hyper-test',
   full_name: 'Cloudoki/cn-hyper-test',
   owner: { name: 'Cloudoki', email: 'hello@cloudoki.com' },
   private: true,
   html_url: 'https://github.com/Cloudoki/cn-hyper-test',
   description: 'Testing tool to Restul API\'s, part of the Hyper platform',
   fork: false,
   url: 'https://github.com/Cloudoki/cn-hyper-test',
   forks_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/forks',
   keys_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/keys{/key_id}',
   collaborators_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/collaborators{/collaborator}',
   teams_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/teams',
   hooks_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/hooks',
   issue_events_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/issues/events{/number}',
   events_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/events',
   assignees_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/assignees{/user}',
   branches_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/branches{/branch}',
   tags_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/tags',
   blobs_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/git/blobs{/sha}',
   git_tags_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/git/tags{/sha}',
   git_refs_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/git/refs{/sha}',
   trees_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/git/trees{/sha}',
   statuses_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/statuses/{sha}',
   languages_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/languages',
   stargazers_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/stargazers',
   contributors_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/contributors',
   subscribers_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/subscribers',
   subscription_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/subscription',
   commits_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/commits{/sha}',
   git_commits_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/git/commits{/sha}',
   comments_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/comments{/number}',
   issue_comment_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/issues/comments{/number}',
   contents_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/contents/{+path}',
   compare_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/compare/{base}...{head}',
   merges_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/merges',
   archive_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/{archive_format}{/ref}',
   downloads_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/downloads',
   issues_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/issues{/number}',
   pulls_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/pulls{/number}',
   milestones_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/milestones{/number}',
   notifications_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/notifications{?since,all,participating}',
   labels_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/labels{/name}',
   releases_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/releases{/id}',
   deployments_url: 'https://api.github.com/repos/Cloudoki/cn-hyper-test/deployments',
   created_at: 1464877710,
   updated_at: '2016-06-02T16:54:14Z',
   pushed_at: 1464967556,
   git_url: 'git://github.com/Cloudoki/cn-hyper-test.git',
   ssh_url: 'git@github.com:Cloudoki/cn-hyper-test.git',
   clone_url: 'https://github.com/Cloudoki/cn-hyper-test.git',
   svn_url: 'https://github.com/Cloudoki/cn-hyper-test',
   homepage: null,
   size: 22,
   stargazers_count: 0,
   watchers_count: 0,
   language: 'JavaScript',
   has_issues: true,
   has_downloads: true,
   has_wiki: true,
   has_pages: false,
   forks_count: 0,
   mirror_url: null,
   open_issues_count: 0,
   forks: 0,
   open_issues: 0,
   watchers: 0,
   default_branch: 'master',
   stargazers: 0,
   master_branch: 'master',
   organization: 'Cloudoki' }
  }
